#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    waca-minio-9090-http:
      entrypoints:
        - http-9089
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-minio-9090"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-minio-10101-http:
      entrypoints:
        - http-10100
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-minio-10101"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-80"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-8025"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-web-5173-http:
      entrypoints:
        - http-5172
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-5173"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-web-8080-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-8080"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    waca-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-xhgui-80"
      tls: false
      # middlewares:
      #   - "waca-redirectHttps"
    
    
    
    waca-minio-9090-https:
      entrypoints:
        - http-9090
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-minio-9090"
      
      tls: true
      
    waca-minio-10101-https:
      entrypoints:
        - http-10101
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-minio-10101"
      
      tls: true
      
    
    
    
    
    waca-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-80"
      
      tls: true
      
    waca-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-8025"
      
      tls: true
      
    waca-web-5173-https:
      entrypoints:
        - http-5173
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-5173"
      
      tls: true
      
    waca-web-8080-https:
      entrypoints:
        - http-8081
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-web-8080"
      
      tls: true
      
    
    waca-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^waca\.ddev\.site$`)
      
      service: "waca-xhgui-80"
      
      tls: true
      
    

  middlewares:
    waca-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    waca-minio-9090:
      loadbalancer:
        servers:
          - url: http://ddev-waca-minio:9090
        
    waca-minio-10101:
      loadbalancer:
        servers:
          - url: http://ddev-waca-minio:10101
        
    
    
    waca-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-waca-web:80
        
    waca-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-waca-web:8025
        
    waca-web-5173:
      loadbalancer:
        servers:
          - url: http://ddev-waca-web:5173
        
    waca-web-8080:
      loadbalancer:
        servers:
          - url: http://ddev-waca-web:8080
        
    
    
    
    
    waca-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-waca-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/waca.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/waca.key